# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_effectsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effectsmodel',
            name='effect',
            field=models.FileField(upload_to=b'effects/%Y/%m/%d'),
        ),
    ]
