# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 11:27
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160218_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effectsmodel',
            name='effect',
            field=models.FileField(upload_to=api.models.generate_upload_path),
        ),
    ]
